# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "icmp4em"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jake Douglas", "Fernando Alonso"]
  s.date = "2012-03-23"
  s.description = "Asynchronous implementation of ICMP ping using EventMachine. Can be used to ping many hosts at once in a non-blocking fashion, with callbacks for success, timeout, and host failure/recovery based on specified threshold numbers."
  s.email = "krakatoa1987@gmail.com"
  s.extra_rdoc_files = ["README"]
  s.files = `git ls-files -z`.split("\x0").reject do |f|
    f.match(%r{^(test|spec|features)/})
  end
  s.homepage = "http://github.com/krakatoa/icmp4em"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Asynchronous implementation of ICMP ping over EventMachine"

  s.add_runtime_dependency 'eventmachine'
  s.add_development_dependency 'shoulda'
  s.add_development_dependency 'bundler'
  s.add_development_dependency 'jeweler'
  s.add_development_dependency 'simplecov'
end

